### ISSUE TITLE
`ctrl-shift-p` enabling

### ISSUE THREAD

**Issue by nsmith5** [p-e-w/plotinus#18] opened 2017-03-11 01:59 UTC
Works too well. The level of disappointment I now have to deal with when `ctrl-shift-p` doesn't do anything is unreasonable. Please delete repository as soon as possible. I'm developing a dependency.

**Comment by p-e-w** [comment] 2017-03-12 17:13
> I'm developing a dependency.

That's by design, sorry. Therefore, I'm forced to close this issue as "won't fix". 😺

**Closed by p-e-w** 2017-03-12 17:13 UTC
Labels: wontfix
