### ISSUE TITLE
doesn't work with Pantheon-Files

### ISSUE THREAD

**Issue by sgpthomas** [p-e-w/plotinus#2] opened 2016-11-13 20:19 UTC
When running this with pantheon-files, nothing pops up and in the terminal, `[FATAL 15:18:37.157163] [GLib] g_strsplit: assertion 'string != NULL' failed` is displayed.

**Comment by p-e-w** [comment] 2016-11-14 03:04
While I can't reproduce this, I have found a potential problem in the code and pushed a fix. Could you try whether this change resolves the issue for you?

**Comment by sgpthomas** [comment] 2016-11-14 03:48
yep. it seems to work now. Although it doesn't detect very many things. Although that might be a different issue. It only shows "previous" which doesn't actually work. Let me know if I should file a separate issue about this.

**Comment by p-e-w** [comment] 2016-11-27 05:53
I have made several improvements to command extraction after debugging some Elementary applications. Plotinus should now find many more commands than before.

**Closed by p-e-w** 2016-11-27 05:53 UTC
Labels: bug
