### ISSUE TITLE
Does not work in libreoffice 5.3 with notebookbar and hidden menubar

### ISSUE THREAD

**Issue by bartlibert** [p-e-w/plotinus#16] opened 2017-03-02 08:33 UTC
In libreoffice 5.3, the experimental notebookbar was introduced (https://wiki.documentfoundation.org/Development/NotebookBar). When this is enabled, you can hide the menubar. If this is done, plotinus stops working. If you enable the menubar again, everything works fine.

**Comment by p-e-w** [comment] 2017-03-05 03:33
Plotinus only looks at visible widgets. This behavior could easily be changed, but there is a risk that it would lead to UI elements being picked up that are not intended to be presented to the user (e.g. unfinished menus that are populated in reaction to some event).

**Comment by bartlibert** [comment] 2017-03-06 11:17
Certainly a valid point that I had not thought about. Maybe an option to
make this configurable or only enable it for certain applications? Don't
know how open you are to adding options/configuration?

Op zo 5 mrt. 2017 om 04:33 schreef Philipp Emanuel Weidmann <
notifications@github.com>:

**Comment by p-e-w** [comment] 2017-04-29 14:40
I have pondered the issue some more and decided that this behavior is as intended. Plotinus makes searchable what you see. Thus I am closing this as "won't fix".

**Closed by p-e-w** 2017-04-29 14:40 UTC
Labels: wontfix
