### ISSUE TITLE
gnome doesnt start

### ISSUE THREAD

**Issue by RGPreisschild** [p-e-w/plotinus#28] opened 2017-05-28 17:49 UTC
gnome doesnt start after installing plotinus from AUR. (using XServer)

**Comment by p-e-w** [comment] 2017-06-04 05:15
I'm closing this because it relates to an unofficial AUR package that I cannot support. Please report this problem to the package's maintainer, or, if you can also reproduce with manual installation, file a new issue here with more details.

**Closed by p-e-w** 2017-06-04 05:15 UTC
